version: "3.7"

services:
  accounts:
    build:
      context: services/accounts
    depends_on:
      - accounts-neo4j
    entrypoint: ./entrypoint.sh
    environment:
      - JWT_SECRET=secret
      - NEO4J_HOST=bolt://accounts-neo4j:7687
      - NEO4J_PASSWORD=accounts
      - NEO4J_USER=neo4j
      - PORT=4000

  accounts-neo4j:
    environment:
      - "NEO4J_AUTH=neo4j/accounts"
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"

  gateway:
    depends_on:
      - accounts
      - inventory
      - products
      - reviews
    entrypoint: ./entrypoint.sh
    environment:
      - JWT_SECRET=secret
      - PORT=4000
    image: node:10-alpine
    ports:
      - 4000:4000
    volumes:
      - ./services/gateway:/gateway
    working_dir: /gateway

  inventory:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ./services/inventory:/inventory
    working_dir: /inventory

  products:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ./services/products:/products
    working_dir: /products

  reviews:
    entrypoint: ./entrypoint.sh
    environment:
      - PORT=4000
    image: node:10-alpine
    volumes:
      - ./services/reviews:/reviews
    working_dir: /reviews

  web-app:
    build:
      args:
        - GATEWAY_HOST=http://localhost:4000
      context: services/web-app
    depends_on:
      - gateway
    ports:
      - 3000:80
